### ISSUE TITLE
delete not work

### ISSUE THREAD

**Issue by cobabikin** [thyseus/yii2-message#9]
![nw](https://user-images.githubusercontent.com/17420664/28501075-b945bac8-7006-11e7-8e5f-96b246402b34.PNG)

after delete status not set...

**Comment by thyseus** [comment]
Hey, thanks for reporting. Unfortunately i can not reproduce this issue. Could you elaborate a little bit more what you have done? which DB do you use?

**Comment by cobabikin** [comment]
sorry I'm late..
![capture1](https://user-images.githubusercontent.com/17420664/28725643-aeb5e25c-73f0-11e7-8134-d6838a8c0839.PNG)
![capture2](https://user-images.githubusercontent.com/17420664/28725653-b3e8b984-73f0-11e7-9d82-b828b6952cb2.PNG)

**Comment by thyseus** [comment]
Ah, ok. It is important to not delete the messages physically, because the message would be removed in the outbox of the sender and the inbox of the recipient. This is why we use the status "STATUS_DELETED". The Message will still appear as "sent" in the outbox, but will me hidden in the inbox of the recipient. Some people call this "soft delete".
